### ISSUE TITLE
Editing the code in hvsync_generator.v 

### ISSUE THREAD

**Issue by mohammad-albarham** [gipi/electronics-notes#1]
In " fpga/mojo/VGA/source/hvsync_generator.v " : 

This line is not correct and I think there is an error in the register width : 

wire CounterYmaxed = (CounterY == 525); // 10 + 2 + 33 + 480

If you want to compare CounterY with 525, you need to make a 10 bit width for CounterY instead of 9.

*************************************************

module hvsync_generator(
    input clk,
    output vga_h_sync,
    output vga_v_sync,
    output reg inDisplayArea,
    output reg [9:0] CounterX,
    output reg [9:0] CounterY      // Make the change here
  );

**Comment by gipi** [comment]
Indeed you are right, when I added the simulation in VGAGlyph I discovered the bug and fixed it in that subproject.
